added ShoppingCart entity
TemkaHillfinger/book-store pull request #12
Opened 2024-04-10 09:52 UTC by TemkaHillfinger

added CartItem entity

2024-04-10 11:02 UTC, MAMentorFX requested changes

2024-04-10 11:02 UTC, MAMentorFX commented on src/main/java/bookstore/service/cart/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCartDto updateCartItemQuantity(Long cartItemId, UpdateCartItemRequest request) {
transaction

2024-04-10 11:02 UTC, MAMentorFX commented on src/main/resources/db/changelog/changes/07-create-cart_items-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false
                    
```

2024-04-10 11:02 UTC, MAMentorFX commented on src/main/resources/db/changelog/changes/08-create-shopping-carts-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false
                    
```

2024-04-10 11:02 UTC, MAMentorFX commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/08-create-shopping-carts-table.yaml
```suggestion
      file: db/changelog/changes/08-create-shopping-carts-table.yaml
      
```

2024-04-11 10:56 UTC, kozhukhovsky approved these changes

2024-04-12 07:28 UTC, merged