Spring Data JPA
TemkaHillfinger/book-store pull request #4
Opened 2024-01-25 13:12 UTC by TemkaHillfinger

2024-02-02 11:04 UTC, olekskov requested changes
1. Task requirement "Implement soft delete concept for the Book entity" is not implemented
2. PUT: /api/books/{id} (Update a specific book) is not implemented
3. Some comments below

2024-02-02 11:04 UTC, olekskov commented on src/main/java/bookstore/dto/BookDto.java
> +    @Column(name = "author")
why column annotation in DTO?

2024-02-02 11:04 UTC, olekskov commented on src/main/java/bookstore/dto/CreateBookRequestDto.java
> +    @Column(name = "author")
same question

2024-02-12 11:42 UTC, Vasul-Pankiv requested changes

2024-02-12 11:42 UTC, Vasul-Pankiv commented on src/main/java/bookstore/model/Book.java
> +
empty line

2024-02-12 11:42 UTC, Vasul-Pankiv commented on src/main/java/bookstore/model/Book.java
>      private String coverImage;
in db comn has another name, Please add @Column annotation with necessary param

2024-02-12 11:42 UTC, Vasul-Pankiv commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yaml
add empty line to the end of file

2024-02-12 12:17 UTC, kozhukhovsky approved these changes

2024-02-13 10:59 UTC, merged